# Generated by Django 5.2.5 on 2025-09-23 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(default='Unknown', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('video', models.FileField(blank=True, null=True, upload_to='crime_videos/')),
                ('date_of_incident', models.DateField(help_text='Format: DD-MM-YYYY')),
                ('time_of_incident', models.TimeField(help_text='Format: HH:MM')),
                ('victim_age_group', models.CharField(choices=[('under_18', 'Under 18'), ('18_25', '18-25'), ('26_40', '26-40'), ('41_60', '41-60'), ('above_60', 'Above 60')], help_text='Select victim age group', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('first_touched_at', models.DateTimeField(blank=True, help_text='When officer first opened or updated this report', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('resolution_status', models.CharField(choices=[('Pending', 'Pending'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved')], default='Pending', max_length=30)),
                ('severity_score', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ai_status', models.CharField(default='Pending', max_length=50)),
                ('ai_progress', models.IntegerField(default=0)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.userprofile')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
