# Generated by Django 4.2.24 on 2025-09-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_userprofile_role_crimereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='photos/')),
                ('is_ai_generated', models.BooleanField(default=False, help_text='True if detected as AI-generated')),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Flagged', 'Flagged')], default='Pending', max_length=20)),
                ('deepfake_suspected', models.BooleanField(default=False)),
                ('weapon_detected', models.BooleanField(default=False)),
                ('violence_detected', models.BooleanField(default=False)),
                ('ai_confidence_score', models.FloatField(blank=True, help_text='0.0 to 1.0 probability score', null=True)),
                ('crime_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='myapp.crimereport')),
            ],
        ),
    ]
