# Generated by Django 4.2.24 on 2025-10-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_crimephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disapproval_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('Inspector', 'Inspector')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='forgot_password_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liveness_frame',
            field=models.ImageField(blank=True, null=True, upload_to='liveness_frames/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liveness_video',
            field=models.FileField(blank=True, null=True, upload_to='liveness_videos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('police', 'Police')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialty',
            field=models.CharField(blank=True, choices=[('Cyber Crime', 'Cyber Crime'), ('Theft', 'Theft'), ('Assault', 'Assault'), ('Fraud', 'Fraud'), ('Narcotics', 'Narcotics'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='station_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
