# Generated by Django 4.2.24 on 2025-10-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_crimereport_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
