# Generated by Django 4.2.24 on 2026-03-24 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_policestation_alter_userprofile_role_officerfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimephoto',
            name='ai_confidence_score',
        ),
        migrations.RemoveField(
            model_name='crimephoto',
            name='deepfake_suspected',
        ),
        migrations.RemoveField(
            model_name='crimephoto',
            name='violence_detected',
        ),
        migrations.RemoveField(
            model_name='crimephoto',
            name='weapon_detected',
        ),
        migrations.RemoveField(
            model_name='officerfeedback',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='crimephoto',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='date_of_incident',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='first_touched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='time_of_incident',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='victim_age_group',
            field=models.CharField(choices=[('under_18', 'Under 18'), ('18_25', '18-25'), ('26_40', '26-40'), ('41_60', '41-60'), ('above_60', 'Above 60')], max_length=20),
        ),
        migrations.AlterField(
            model_name='officerfeedback',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile'),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
