# Generated by Django 4.2.24 on 2026-03-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_crimephoto_ai_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cases_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='star_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
