# Generated by Django 4.2.24 on 2026-03-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_userprofile_cases_completed_userprofile_star_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
