# Generated by Django 4.2.24 on 2026-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_crimereport_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
